wallpaper {
	monitor = eDP-1
	path = ~/.config/wallpapers/varanda.jpg
	fit_mode = fill
}

wallpaper {
	monitor = DP-1
	path = ~/.config/wallpapers/milesmorales.jpeg
	fit_mode = fill
}

splash = false
